name: BalloonsPlus
main: be.shark_zekrom.Main
version: '${project.version}'
api-version: 1.13
description: Create a balloon
commands:
  balloonsplus:
    description: balloons

permissions:
  ballonsplus.equip:
    description: show ballons gui
    default: true
  balloonsplus.unequip:
    description: unequip balloon
    default: true
  balloonsplus.reload:
    description: reload configuration file
    default: op