# BalloonsPlus
# Spigot-Paper plugin that allow players to equip balloons

ShowOnlyBalloonsWithPermission: true

ShowParticlesBalloonsOnRemove: true

Messages:
  BalloonPrefix: "§b[Balloons+] "
  BalloonReload: "§bSuccessfully reloaded!"
  BalloonsSummoned: "§bBalloons summoned."
  BalloonsRemoved: "§bBalloons removed."
  BalloonsMenuName: "Balloons Menu"
  BalloonsMenuPrevious: "§7« §ePrevious"
  BalloonsMenuNext: "§eNext §7»"
  BalloonsMenuRemove: "§cRemove balloon"
  BalloonsMenuClickToSummon: "§6» §eClick to summon"
  BalloonsMenuNoPermissionToSummon: "§cNo permission to summon"

# The name is arbitrary, ofc you can't have twho balloons with same name.
# If isDefault is true everyone can use the relative balloon. If isDefault is false permission is needed.
# Balloon permission: balloonsplus.<balloon_name>.balloon
# Get balloons key (head VALUE) from https://minecraft-heads.com/
Balloons:
  Red_Balloon:
    isDefault: true
    key: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNTJkZDExZGEwNDI1MmY3NmI2OTM0YmMyNjYxMmY1NGYyNjRmMzBlZWQ3NGRmODk5NDEyMDllMTkxYmViYzBhMiJ9fX0="
  Pink_Balloon:
    isDefault: true
    key: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNGY4NTUyMmVlODE1ZDExMDU4N2ZmZmM3NDExM2Y0MTlkOTI5NTk4ZTI0NjNiOGNlOWQzOWNhYTlmYjZmZjVhYiJ9fX0="
  Green_Balloon:
    isDefault: true
    key: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYTI2ZWM3Y2QzYjZhZTI0OTk5NzEzN2MxYjk0ODY3YzY2ZTk3NDk5ZGEwNzFiZjUwYWRmZDM3MDM0MTMyZmEwMyJ9fX0="
  Blue_Balloon:
    isDefault: true
    key: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZjg2OGU2YTVjNGE0NDVkNjBhMzA1MGI1YmVjMWQzN2FmMWIyNTk0Mzc0NWQyZDQ3OTgwMGM4NDM2NDg4MDY1YSJ9fX0="
  Orange_Balloon:
    isDefault: true
    key: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZWVmMTYyZGVmODQ1YWEzZGM3ZDQ2Y2QwOGE3YmY5NWJiZGZkMzJkMzgxMjE1YWE0MWJmZmFkNTIyNDI5ODcyOCJ9fX0="
  Orange_G:
    isDefault: true
    key: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNWMyMDhkN2RiN2RiODA3MDVlOTQ0YWZjZWMxOWE5NDA5ZjA0N2ViMTgxZWMyNWFlZGVkOWNlMjhlYjM2NjVhMSJ9fX0="
  eshark_zekrom:
    isDefault: true
    key: "ewogICJ0aW1lc3RhbXAiIDogMTYyNzA1NDA1Mjg5MCwKICAicHJvZmlsZUlkIiA6ICIzMzNhMjQ3ODk3MTE0MDA2YTE3ZDFmOTU4ZjhkMDZmMSIsCiAgInByb2ZpbGVOYW1lIiA6ICJzaGFya196ZWtyb20iLAogICJzaWduYXR1cmVSZXF1aXJlZCIgOiB0cnVlLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvZDBjNzAyODQyZTc0MDM4ODA0YzYzNDUwZTU4YzI4ZTgwOGJjNmFiY2I1M2EwZjI0NTRjN2FkMmRkMDUwNmFhMyIKICAgIH0KICB9Cn0"
  Duck_Employee :
    isDefault: true
    key: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYzFkNzE2ODc5YWViZGVmYzc3MWQwZjZhZDViMTdlNGMxMjQyYzkyMjZkNTdkNDVkNzEwODZmMWE1NDEwNTFjMiJ9fX0="
  Glow_Slime:
    isDefault: true
    key: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMmEyMDEwMWYyOTZiZDZiNWI3YTEzNzNhNGIyNDU2MjE0OTQzYzlkOTdkY2Q2MjZmNzE1ZDRhMGUwNTIyODYxYyJ9fX0="
  Dr_Lizard:
    isDefault: true
    key: "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNDEyZGQ1ZDQwMDg3YWU0NTFjNjAzNDVlY2I3MWY1ZTAxOGI3ZWYxOTllZDcxZTVmNGU3Zjc3ZmUxNzAzZDMyMCJ9fX0="