name: BalloonsPlus
main: be.shark_zekrom.Main
version: '1.7.2-fixed'
api-version: 1.13
description: Create a balloon
commands:
  balloonsplus:
    description: BalloonsPlus main command
    aliases:
      - balloon

permissions:
  ballonsplus.equip:
    description: show ballons gui
    default: true
  balloonsplus.unequip:
    description: unequip balloon
    default: true
  balloonsplus.reload:
    description: reload configuration file
    default: op
  balloonsplus.default.balloon:
    description: default balloon permission
    default: true